# Taken from: https://github.com/brandtbucher/travis-python-matrix

# CPython 3.5.2 / CPython 3.6.8 / CPython 3.7.3
# Ubuntu Xenial 16.04 / Windows Server 1803 / macOS 10.13

# Just comment out any matrix entries you don't need.

language: shell

matrix:

  include:

    - name: CPython 3.6.8 on Ubuntu Xenial 16.04
      python: 3.6.8
      dist: xenial
      language: python

    - name: CPython 3.7.3 on Ubuntu Xenial 16.04
      python: 3.7.3
      dist: xenial
      language: python


    - name: CPython 3.6.8 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.6.8
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - name: CPython 3.7.3 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.7.3
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH


    - name: CPython 3.6.8 on macOS 10.13
      os: osx
      before_install: brew upgrade pyenv; pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8

    - name: CPython 3.7.3 on macOS 10.13
      os: osx
      before_install: brew upgrade pyenv; pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3

# Change anything below to suit your CI needs.
# Python and pip exectuables are just named "python" and "pip" on all platforms!

install:
  - pip install codecov pytest-cov
  - pip install -r requirements-test.txt
  - pip install setuptools wheel

before_script:
  - python setup.py develop

script:
  - pytest --cov=static_frame

after_script:
  - python setup.py sdist bdist_wheel

after_success:
  - codecov
