name: Test

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: ['ubuntu-18.04', 'windows-2019', 'macos-10.15']
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}

      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.35.1
        pip install numpy==1.16.5
        pip install Cython==0.29.13
        pip install setuptools==41.2.0
        pip install -r requirements-test.txt

    - name: Invoke Test
      run: inv test
